sudo: false
  
language: java

before_install:
  - echo "TERM $TERM"
  - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
  - . ./install-jdk.sh -F 10 -L GPL -C

install: true
script: true

